### ISSUE TITLE
Search Button Not Working

### ISSUE THREAD

**Issue by Sanjaya-Samudra** [Sanjaya-Samudra/JavaFX-Maven-Practice-Project-2#1]
![Screenshot 2024-09-18 233630](https://github.com/user-attachments/assets/c4692406-bc58-402b-9d68-b4e76a2457a1)
![image](https://github.com/user-attachments/assets/1c675a20-3bf3-4228-bf3b-38fc2d099985)

**Still doing a research to figure out what to do with it.
Finding best solution to solve the problem.**

**Comment by SanjayaSamudra** [comment]
Looking for a solution.

**Comment by Sanjaya-Samudra** [comment]
**Fully Functional Search Button Added With Validations.**
