### ISSUE TITLE
Place Order Button

### ISSUE THREAD

**Issue by Sanjaya-Samudra** [Sanjaya-Samudra/JavaFX-Maven-Practice-Project-2#3]
**Kind reminder to everyone that the "Place Order" button has not been set up yet. 
I am working on it and will update the project soon.**

![image](https://github.com/user-attachments/assets/be4a1820-5851-4adf-b94c-1f8604b41bec)

**Comment by SanjayaSamudra** [comment]
Please update the  **"Net Total"** also.

**Comment by Sanjaya-Samudra** [comment]
The **_NET Total_** calculation has been successfully updated.

**Comment by Sanjaya-Samudra** [comment]
**"Place Order"** button was implemented successfully and updated the code.
Finally **"transaction"** part completed.
